/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author K O O
 */
public class Debug_1 extends javax.swing.JFrame {

    /**
     * Creates new form Debug_1
     */
    public Debug_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_Sum = new javax.swing.JButton();
        Buttom_Minus = new javax.swing.JButton();
        Buttom_Mutiply = new javax.swing.JButton();
        Buttom_Divide = new javax.swing.JButton();
        Buttom_Pow = new javax.swing.JButton();
        Buttom_Combination = new javax.swing.JButton();
        Buttom_Permutation = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Input_variableA = new javax.swing.JTextField();
        Input_variableB = new javax.swing.JTextField();
        input3_variable = new javax.swing.JTextField();
        input3 = new javax.swing.JLabel();
        ketqua = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        ButtomResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button_Sum.setText("Sum");
        Button_Sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SumActionPerformed(evt);
            }
        });

        Buttom_Minus.setText("Minus");
        Buttom_Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttom_MinusActionPerformed(evt);
            }
        });

        Buttom_Mutiply.setText("Mutiply");
        Buttom_Mutiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttom_MutiplyActionPerformed(evt);
            }
        });

        Buttom_Divide.setText("Divide");
        Buttom_Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttom_DivideActionPerformed(evt);
            }
        });

        Buttom_Pow.setText("Pow");
        Buttom_Pow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttom_PowActionPerformed(evt);
            }
        });

        Buttom_Combination.setText("Combination");
        Buttom_Combination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttom_CombinationActionPerformed(evt);
            }
        });

        Buttom_Permutation.setText("Permutation");
        Buttom_Permutation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttom_PermutationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Buttom_Permutation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buttom_Combination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buttom_Pow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Sum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buttom_Minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buttom_Mutiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buttom_Divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Button_Sum)
                .addGap(18, 18, 18)
                .addComponent(Buttom_Minus)
                .addGap(18, 18, 18)
                .addComponent(Buttom_Mutiply)
                .addGap(18, 18, 18)
                .addComponent(Buttom_Divide)
                .addGap(18, 18, 18)
                .addComponent(Buttom_Pow)
                .addGap(18, 18, 18)
                .addComponent(Buttom_Combination)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Buttom_Permutation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Input1");

        jLabel3.setText("Input2");

        Input_variableA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_variableAActionPerformed(evt);
            }
        });

        input3_variable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input3_variableActionPerformed(evt);
            }
        });

        input3.setText("Input3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(input3))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input3_variable)
                    .addComponent(Input_variableA)
                    .addComponent(Input_variableB, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Input_variableA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Input_variableB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input3_variable, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input3))
                .addGap(46, 46, 46))
        );

        Title.setBackground(new java.awt.Color(102, 102, 255));
        Title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 0, 204));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Máy Tính Đơn Giản");

        ButtomResult.setText("Kết Quả");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtomResult)
                .addGap(18, 18, 18)
                .addComponent(ketqua, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ketqua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtomResult))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Input_variableAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_variableAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_variableAActionPerformed

    private void Button_SumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SumActionPerformed
        double Input1 = Double.parseDouble(Input_variableA.getText());
        double Input2 = Double.parseDouble(Input_variableB.getText());
        double Input3 = Double.parseDouble(input3_variable.getText());
        double Sum = 0;
        Sum = Input2+Input1+Input3;
        ketqua.setText(Sum+ " ");
    }//GEN-LAST:event_Button_SumActionPerformed

    private void Buttom_MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttom_MinusActionPerformed
        // TODO add your handling code here:
        double Input1 = Double.parseDouble(Input_variableA.getText());
        double Input2 = Double.parseDouble(Input_variableB.getText());
        double Minus = 0;
        Minus = Input1-Input2;
        ketqua.setText(Minus+ " ");
    }//GEN-LAST:event_Buttom_MinusActionPerformed

    private void Buttom_MutiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttom_MutiplyActionPerformed
        // TODO add your handling code here:
        double Input1 = Double.parseDouble(Input_variableA.getText());
        double Input2 = Double.parseDouble(Input_variableB.getText());
        double Mutiply = 0;
        Mutiply = Input1*Input2;
        ketqua.setText(Mutiply+ " ");
    }//GEN-LAST:event_Buttom_MutiplyActionPerformed

    private void Buttom_DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttom_DivideActionPerformed
        // TODO add your handling code here:
        double Input1 = Integer.parseInt(Input_variableA.getText());
        double Input2 = Integer.parseInt(Input_variableB.getText());
        double Divide = 0;
        Divide = Input1/Input2;
        ketqua.setText(Divide+ " ");
    }//GEN-LAST:event_Buttom_DivideActionPerformed

    private void Buttom_PowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttom_PowActionPerformed
        // TODO add your handling code here:
        double Input1 = Double.parseDouble(Input_variableA.getText());
        double Input2 = Double.parseDouble(Input_variableB.getText());
        double Pow = 0;
        Pow = Math.pow(Input1, Input2);
        ketqua.setText(Pow+ " ");
    }//GEN-LAST:event_Buttom_PowActionPerformed

    private void Buttom_CombinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttom_CombinationActionPerformed
            // TODO add your handling code here:
        double Input1 = Double.parseDouble(Input_variableA.getText());
        double Input2 = Double.parseDouble(Input_variableB.getText());
        double Combination = 0, Numerator = 1, Denominator = 1;
        double Temporary_variable = Input1-Input2;
        for(int i = 1 ; i<=Input1; i++){
            Numerator = Numerator*i;
        }
//        System.out.println(Numerator);
        for(int i = 1 ; i<=Temporary_variable; i++){
            Denominator = Denominator*i;
        }
//        System.out.println(Denominator);
        Combination = Numerator/Denominator;
        ketqua.setText(Combination + " ");
    }//GEN-LAST:event_Buttom_CombinationActionPerformed

    private void Buttom_PermutationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttom_PermutationActionPerformed
        // TODO add your handling code here:
        double Input1 = Double.parseDouble(Input_variableA.getText());
        double Input2 = Double.parseDouble(Input_variableB.getText());
        double Permutation = 0, Numerator = 1, Denominator = 1, k = 1;
        double Temporary_variable = Input1-Input2;
        for(int i = 1 ; i<=Input1; i++){
            Numerator = Numerator*i;
        }
        for(int i = 1 ; i<=Input2;i++){
            k =k*i;
        }
        for(int i = 1 ; i<=Temporary_variable; i++){
            Denominator = Denominator*i;
        }
        Permutation = Numerator/(k*Denominator);
        ketqua.setText(Permutation + " ");
    }//GEN-LAST:event_Buttom_PermutationActionPerformed

    private void input3_variableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input3_variableActionPerformed
        // TODO add your handling code here:
        
   
    }//GEN-LAST:event_input3_variableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Debug_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Debug_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Debug_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Debug_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Debug_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtomResult;
    private javax.swing.JButton Buttom_Combination;
    private javax.swing.JButton Buttom_Divide;
    private javax.swing.JButton Buttom_Minus;
    private javax.swing.JButton Buttom_Mutiply;
    private javax.swing.JButton Buttom_Permutation;
    private javax.swing.JButton Buttom_Pow;
    private javax.swing.JButton Button_Sum;
    private javax.swing.JTextField Input_variableA;
    private javax.swing.JTextField Input_variableB;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel input3;
    private javax.swing.JTextField input3_variable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField ketqua;
    // End of variables declaration//GEN-END:variables
}
